services:
  postgres:
    image: postgres:18
    container_name: postgres_test
    ports:
      - "5432:5432"
    volumes:
      - progresDB_test:/var/lib/postgresql
    env_file:
      - .env.test

volumes:
  progresDB_test:
